---
- name: 'Install squid'
  yum:
    name: 'squid'
    state: 'present'
    update_cache: true

- name: 'Open firewall port for squid'
  ansible.posix.firewalld:
    port: '3128/tcp'
    permanent: true
    state: 'enabled'

- name: 'Ensure that /etc/squid/conf.d folder exists'
  file:
    path: '/etc/squid/conf.d/'
    owner: 'root'
    group: 'root'
    mode: 0755
    state: 'directory'

- name: "Update custom squid configurations"
  template:
    src: 'template.conf.j2'
    dest: '/etc/squid/conf.d/{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: restart squid
  vars:
    squid_custom_config: "{{ item }}"
  loop: "{{ squid_custom_config }}"
  when: squid_custom_config is defined

- name: 'Check if squid sub-modules are present'
  find:
    paths: '/etc/squid/conf.d/'
    patterns: '*.conf'
  register: find

- name: 'Ensure there is at least 1 sub-module present'
  file:
    path: '/etc/squid/conf.d/default.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
    state: 'touch'
  when: find.matched == 0

- name: 'Update squid config/acls'
  template:
    src: 'squid.conf.j2'
    dest: '/etc/squid/squid.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: restart squid
