---
- name: 'Install squid'
  yum:
    name: 'squid'
    state: 'present'
    update_cache: true

- name: 'Ensure /etc/squid/conf.d folder exists'
  file:
    path: '/etc/squid/conf.d/'
    owner: 'root'
    group: 'root'
    mode: 0755
    state: 'directory'

- name: "Update custom squid configuration for {{ config_name }}"
  template:
    src: 'template.conf.j2'
    dest: '/etc/squid/conf.d/{{ config_name }}.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: restart squid
  when: config_name != 'squid'

- name: 'Check if squid sub-modules are present'
  find:
    paths: '/etc/squid/conf.d/'
    patterns: '*.conf'
  register: find

- name: 'Update squid config/acls'
  template:
    src: 'squid.conf.j2'
    dest: '/etc/squid/squid.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: restart squid
  when: config_name == 'squid'
